services:
  vc-radio-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vc_radio_local
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: main.py
      FLASK_DEBUG: "1"

